//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatabaseContext.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following booking with PureSmile has been cancelled:
        ///&lt;ul&gt;
        ///  &lt;li&gt;Clinlic: {0}, {1}&lt;/li&gt;
        ///  &lt;li&gt;Clinlic address: {2}, {3} {4}&lt;/li&gt;
        ///  &lt;li&gt;Date &amp; time: {5}&lt;/li&gt;
        ///  &lt;li&gt;Treatment: {6}&lt;/li&gt;
        ///  &lt;li&gt;Client name: {7}&lt;/li&gt;
        ///  &lt;li&gt;Client phone: {8}&lt;/li&gt;
        ///  &lt;li&gt;Client email: {9}&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string BookingCanceled {
            get {
                return ResourceManager.GetString("BookingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot;&gt;New booking&lt;/a&gt; has been created:
        ///&lt;ul&gt;
        ///    &lt;li&gt;
        ///        Clinic: {1}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Date &amp; time: {2}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Treatment: {3}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Client name: {4}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Client phone: {5}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;Client email: &lt;a href=&quot;mailto:{6}&quot;&gt;{6}&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///.
        /// </summary>
        public static string BookingCreatedAdmin {
            get {
                return ResourceManager.GetString("BookingCreatedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot;&gt;New booking&lt;/a&gt; has been created:
        ///&lt;ul&gt;
        ///    &lt;li&gt;
        ///        Clinic: {1}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Date &amp; time: {2}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Treatment: {3}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Client name: {4}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Client phone: {5}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;Client email: &lt;a href=&quot;mailto:{6}&quot;&gt;{6}&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string BookingCreatedClient {
            get {
                return ResourceManager.GetString("BookingCreatedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot;&gt;New booking&lt;/a&gt; has been created:
        ///&lt;ul&gt;
        ///  &lt;li&gt;
        ///    Clinic: {1}
        ///  &lt;/li&gt;
        ///  &lt;li&gt;
        ///    Date &amp; time: {2}
        ///  &lt;/li&gt;
        ///  &lt;li&gt;
        ///    Treatment: {3}
        ///  &lt;/li&gt;
        ///  &lt;li&gt;
        ///    Client name: {4}
        ///  &lt;/li&gt;
        ///  &lt;li&gt;
        ///    Client phone: {5}
        ///  &lt;/li&gt;
        ///  &lt;li&gt;Client email: &lt;a href=&quot;mailto:{6}&quot;&gt;{6}&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;a href=&quot;{7}&quot;&gt;Login&lt;/a&gt; to the site or &lt;a href=&quot;{8}&quot;&gt;Restore password&lt;/a&gt;.
        /// </summary>
        public static string BookingCreatedClientForgotten {
            get {
                return ResourceManager.GetString("BookingCreatedClientForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot;&gt;New booking&lt;/a&gt; has been created:
        ///&lt;ul&gt;
        ///    &lt;li&gt;
        ///        Clinic: {1}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Date &amp; time: {2}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Treatment: {3}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Client name: {4}
        ///    &lt;/li&gt;
        ///  &lt;li&gt;
        ///    Client phone: {5}
        ///  &lt;/li&gt;
        ///  &lt;li&gt;&lt;a href=&quot;{7}&quot;&gt;Confirm&lt;/a&gt;&lt;/li&gt;
        ///  &lt;li&gt;&lt;a href=&quot;{8}&quot;&gt;Decline&lt;/a&gt;&lt;/li&gt;
        ///    &lt;li&gt;Client email: &lt;a href=&quot;mailto:{6}&quot;&gt;{6}&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///.
        /// </summary>
        public static string BookingCreatedClinic {
            get {
                return ResourceManager.GetString("BookingCreatedClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1},&lt;br /&gt;&lt;br /&gt;
        ///You have been selected the {2} in the {3} clinic at {4} {5}.&lt;br /&gt;
        ///We will hold your booking for 15 minutes for your payment complete.&lt;br/&gt;
        ///(If you are did not any bookings, ignore this message.)&lt;br /&gt;&lt;br /&gt;
        ///Best regards, &lt;a href=&quot;https://www.puresmile.com.au/&quot;&gt;PureSmile&lt;/a&gt;
        ///&lt;img title=&quot;Pure Smile&quot; alt=&quot;Pure Smile&quot; src=&quot;https://www.puresmile.com.au/wp-content/themes/puresmile/dist/images/PureSmile_logo.png&quot;/&gt;
        ///.
        /// </summary>
        public static string BookingNotofication {
            get {
                return ResourceManager.GetString("BookingNotofication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refund has been made to the following booking with PureSmile:
        ///&lt;ul&gt;
        ///  &lt;li&gt;Clinlic: {0}, {1}&lt;/li&gt;
        ///  &lt;li&gt;Clinlic address: {2}, {3} {4}&lt;/li&gt;
        ///  &lt;li&gt;Date &amp; time: {5}&lt;/li&gt;
        ///  &lt;li&gt;Treatment: {6}&lt;/li&gt;
        ///  &lt;li&gt;Booking amount: ${7}&lt;/li&gt;
        ///  &lt;li&gt;Amount paid: {8}&lt;/li&gt;
        ///  &lt;li&gt;Client name: {9}&lt;/li&gt;
        ///  &lt;li&gt;Client phone: {10}&lt;/li&gt;
        ///  &lt;li&gt;Client email: {11}&lt;/li&gt;
        ///  &lt;li&gt;Amount refunded: ${12}&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string BookingRefund {
            get {
                return ResourceManager.GetString("BookingRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot;&gt;New booking&lt;/a&gt; has been created:
        ///&lt;ul&gt;
        ///    &lt;li&gt;
        ///        Clinic: {1}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Date &amp; time: {2}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Treatment: {3}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Client name: {4}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Client phone: {5}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;Client email: &lt;a href=&quot;mailto:{6}&quot;&gt;{6}&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///.
        /// </summary>
        public static string BookingUpdatedAdmin {
            get {
                return ResourceManager.GetString("BookingUpdatedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot;&gt;New booking&lt;/a&gt; has been created:
        ///&lt;ul&gt;
        ///    &lt;li&gt;
        ///        Clinic: {1}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Date &amp; time: {2}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Treatment: {3}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Client name: {4}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Client phone: {5}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;Client email: &lt;a href=&quot;mailto:{6}&quot;&gt;{6}&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string BookingUpdatedClient {
            get {
                return ResourceManager.GetString("BookingUpdatedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot;&gt;New booking&lt;/a&gt; has been created:
        ///&lt;ul&gt;
        ///    &lt;li&gt;
        ///        Clinic: {1}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Date &amp; time: {2}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Treatment: {3}
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///        Client name: {4}
        ///    &lt;/li&gt;
        ///  &lt;li&gt;
        ///    Client phone: {5}
        ///  &lt;/li&gt;
        ///  &lt;li&gt;&lt;a href=&quot;{7}&quot;&gt;Confirm&lt;/a&gt;&lt;/li&gt;
        ///  &lt;li&gt;&lt;a href=&quot;{8}&quot;&gt;Decline&lt;/a&gt;&lt;/li&gt;
        ///    &lt;li&gt;Client email: &lt;a href=&quot;mailto:{6}&quot;&gt;{6}&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///.
        /// </summary>
        public static string BookingUpdatedClinic {
            get {
                return ResourceManager.GetString("BookingUpdatedClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1},&lt;br /&gt;&lt;br /&gt;
        ///We have created account for your convenience so you could manage your bookings. Please user the following to login into &lt;a href=&quot;{2}&quot;&gt;PureSmile web stie&lt;/a&gt;:&lt;br/&gt;
        ///Login: {3}&lt;br/&gt;
        ///Password: {4}&lt;br/&gt;&lt;br/&gt;
        ///Your bookings will available on your account page.&lt;br/&gt;&lt;br/&gt;
        ///Please confirm your email address by following &lt;a href=&quot;{5}&quot;&gt;link&lt;/a&gt;&lt;br/&gt;
        ///Best regards,&lt;br /&gt;&lt;br /&gt;
        ///&lt;a href=&quot;https://www.puresmile.com.au/&quot;&gt;PureSmile&lt;/a&gt;
        ///&lt;img title=&quot;Pure Smile&quot; alt=&quot;Pure Smile&quot; src=&quot;https://www.p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreationAndEmailConfirmation {
            get {
                return ResourceManager.GetString("CreationAndEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1},&lt;br/&gt;&lt;br /&gt;
        ///New account has been created for {2}&lt;br/&gt;
        ///Please confirm your email address by following the &lt;a target=&quot;_blank&quot; href=&quot;{3}&quot;&gt;link&lt;/a&gt;.&lt;br /&gt;&lt;br /&gt;
        ///Best regards, &lt;a href=&quot;https://www.puresmile.com.au/&quot;&gt;PureSmile&lt;/a&gt;
        ///&lt;img title=&quot;Pure Smile&quot; alt=&quot;Pure Smile&quot; src=&quot;https://www.puresmile.com.au/wp-content/themes/puresmile/dist/images/PureSmile_logo.png&quot; /&gt;.
        /// </summary>
        public static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking with PureSmile has been paid successfully:
        ///&lt;ul&gt;
        ///    &lt;li&gt;Clinlic: {0}, {1}&lt;/li&gt;
        ///    &lt;li&gt;Clinlic address: {2}, {3} {4}&lt;/li&gt;
        ///    &lt;li&gt;Date &amp; time: {5}&lt;/li&gt;
        ///    &lt;li&gt;Treatment: {6}&lt;/li&gt;
        ///    &lt;li&gt;Client name: {7}&lt;/li&gt;
        ///    &lt;li&gt;Booking amount: {8}&lt;/li&gt;
        ///    &lt;li&gt;Amount paid: {9}&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string ReceiptPayment {
            get {
                return ResourceManager.GetString("ReceiptPayment", resourceCulture);
            }
        }
    }
}
